### ISSUE TITLE
API设计

### ISSUE THREAD

**Issue by sunlei33** [qwebfe/strapi-dailysurvey#1]
[URL](https://easydoc.soft.360.cn/doc?project=1ba3f772e9d1ce67fa19ddacfa271508&doc=10cd96bf37e36013f1cfe690ab10546f&config=toc_title)

**Comment by sunlei33** [comment]
@LuChunYu GET /survey/last这个API是不是新增1个参数表示版本，这样管理员可以发布多个版本文件出来？另外，还需要一个防止csrf攻击的API去获取Token，看看strapi里是不是存在的

**Comment by LuChunYu** [comment]
/survey/last 是获取最后一个调查模版进行页面的渲染，如果发布多个，用户访问的时候并不知道有那些模版呀？这里需要考虑模版标记哪个生效么？
防止csrf攻击的API去获取Token，是指每次都动态生成tocken，校验通过再返回内容么？

**Comment by sunlei33** [comment]
> /survey/last 是获取最后一个调查模版进行页面的渲染，如果发布多个，用户访问的时候并不知道有那些模版呀？这里需要考虑模版标记哪个生效么？
> 防止csrf攻击的API去获取Token，是指每次都动态生成tocken，校验通过再返回内容么？

生成新的二维码带入一个版本参数？
每次小程序初始化时调用
